// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LibroSwap.Migrations
{
    [DbContext(typeof(LibroContext))]
    partial class LibroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("author_name");

                    b.Property<string>("AuthorSurname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("author_surname");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Софія",
                            AuthorSurname = "Андрухович"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Оксана",
                            AuthorSurname = "Забужко"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Луїза",
                            AuthorSurname = "Хей"
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Вадим",
                            AuthorSurname = "Зеланд"
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "Джоан",
                            AuthorSurname = "Роулінг"
                        });
                });

            modelBuilder.Entity("DAL.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("author_id");

                    b.Property<int>("BookCoverageId")
                        .HasColumnType("int")
                        .HasColumnName("book_coverage_id");

                    b.Property<int>("BookhouseId")
                        .HasColumnType("int")
                        .HasColumnName("bookhouse_id");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.Property<int>("CurrentOwnerId")
                        .HasColumnType("int")
                        .HasColumnName("current_owner_id");

                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasColumnName("genre_id");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int")
                        .HasColumnName("language_id");

                    b.Property<long>("Pages")
                        .HasColumnType("bigint");

                    b.Property<int?>("SecondaryGenreId")
                        .HasColumnType("int")
                        .HasColumnName("secondary_genre_id");

                    b.Property<int?>("TertiaryGenreId")
                        .HasColumnType("int")
                        .HasColumnName("tertiary_genre_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<bool>("Translation")
                        .HasColumnType("bit");

                    b.Property<int?>("TranslatorId")
                        .HasColumnType("int")
                        .HasColumnName("translator_id");

                    b.Property<long>("Year")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("BookCoverageId");

                    b.HasIndex("BookhouseId");

                    b.HasIndex("CityId");

                    b.HasIndex("CurrentOwnerId");

                    b.HasIndex("GenreId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("SecondaryGenreId");

                    b.HasIndex("TertiaryGenreId");

                    b.HasIndex("TranslatorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            BookCoverageId = 1,
                            BookhouseId = 1,
                            CityId = 4,
                            CurrentOwnerId = 4,
                            GenreId = 1,
                            LanguageId = 1,
                            Pages = 829L,
                            Title = "Амадока",
                            Translation = false,
                            Year = 2020L
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 5,
                            BookCoverageId = 1,
                            BookhouseId = 2,
                            CityId = 1,
                            CurrentOwnerId = 2,
                            GenreId = 1,
                            LanguageId = 1,
                            Pages = 815L,
                            Title = "Гаррі Поттер і Орден Фенікса",
                            Translation = true,
                            TranslatorId = 1,
                            Year = 2003L
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 5,
                            BookCoverageId = 2,
                            BookhouseId = 3,
                            CityId = 2,
                            CurrentOwnerId = 1,
                            GenreId = 1,
                            LanguageId = 2,
                            Pages = 766L,
                            Title = "Harry Potter and the Order of the Phoenix",
                            Translation = false,
                            Year = 2003L
                        });
                });

            modelBuilder.Entity("DAL.Models.BookCoverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoverageName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("coverage_name");

                    b.HasKey("Id");

                    b.ToTable("Coverages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverageName = "Тверда"
                        },
                        new
                        {
                            Id = 2,
                            CoverageName = "М'яка"
                        });
                });

            modelBuilder.Entity("DAL.Models.Bookhouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BookhouseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("bookhouse_name");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Bookhouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookhouseName = "Видавництво Старого Лева",
                            CityId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookhouseName = "Видавництво Івана Малковича „А-ба-ба-га-ла-ма-га",
                            CityId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookhouseName = "Bloomsbury",
                            CityId = 3
                        });
                });

            modelBuilder.Entity("DAL.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("city_code");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("city_name");

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("CountryId");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityCode = "LV",
                            CityName = "Львів",
                            CountryId = 1
                        },
                        new
                        {
                            Id = 2,
                            CityCode = "KYI",
                            CityName = "Київ",
                            CountryId = 1
                        },
                        new
                        {
                            Id = 3,
                            CityCode = "LND",
                            CityName = "Лондон",
                            CountryId = 2
                        },
                        new
                        {
                            Id = 4,
                            CityCode = "PRS",
                            CityName = "Париж",
                            CountryId = 4
                        });
                });

            modelBuilder.Entity("DAL.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("country_code");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("country_name");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "UA",
                            CountryName = "Україна"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "EN",
                            CountryName = "Англія"
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "SCOT",
                            CountryName = "Шотландія"
                        },
                        new
                        {
                            Id = 4,
                            CountryCode = "FR",
                            CountryName = "Франція"
                        });
                });

            modelBuilder.Entity("DAL.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("genre_name");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreName = "Проза"
                        },
                        new
                        {
                            Id = 2,
                            GenreName = "Поезія"
                        },
                        new
                        {
                            Id = 3,
                            GenreName = "Драматургія"
                        });
                });

            modelBuilder.Entity("DAL.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("language_code");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("language_name");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LanguageCode = "UKR",
                            LanguageName = "Українська"
                        },
                        new
                        {
                            Id = 2,
                            LanguageCode = "ENG",
                            LanguageName = "Англійська"
                        },
                        new
                        {
                            Id = 3,
                            LanguageCode = "FRA",
                            LanguageName = "Французька"
                        },
                        new
                        {
                            Id = 4,
                            LanguageCode = "CHI",
                            LanguageName = "Китайська"
                        });
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AboutMe")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("about_me");

                    b.Property<int?>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Recommendation")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("recommendation");

                    b.Property<string>("Surname")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("surname");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutMe = "Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.",
                            CityId = 4,
                            Email = "mbeecker8@deviantart.com",
                            UserName = "Cardify"
                        },
                        new
                        {
                            Id = 2,
                            AboutMe = "Pellentesque ultrices mattis odio. Donec vitae nisi.",
                            CityId = 3,
                            Email = "ktolmanm@php.net",
                            UserName = "Voyatouch"
                        },
                        new
                        {
                            Id = 3,
                            AboutMe = "Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.",
                            Email = "tcothey1t@gmpg.org",
                            UserName = "Konklab"
                        },
                        new
                        {
                            Id = 4,
                            AboutMe = "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.",
                            CityId = 2,
                            Email = "jmundow1y@sfgate.com",
                            UserName = "Ronstring"
                        },
                        new
                        {
                            Id = 5,
                            AboutMe = "In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                            CityId = 1,
                            Email = "tshimman1a@wp.com",
                            UserName = "Flowdesk"
                        });
                });

            modelBuilder.Entity("DAL.Models.Book", b =>
                {
                    b.HasOne("DAL.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.BookCoverage", "BookCoverage")
                        .WithMany("Books")
                        .HasForeignKey("BookCoverageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Bookhouse", "Bookhouse")
                        .WithMany("Books")
                        .HasForeignKey("BookhouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.City", "City")
                        .WithMany("Books")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DAL.Models.User", "CurrentOwner")
                        .WithMany("Books")
                        .HasForeignKey("CurrentOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Language", "Language")
                        .WithMany("Books")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Genre", "SecondaryGenre")
                        .WithMany("SecondaryBooks")
                        .HasForeignKey("SecondaryGenreId");

                    b.HasOne("DAL.Models.Genre", "TertiaryGenre")
                        .WithMany("TertiaryBooks")
                        .HasForeignKey("TertiaryGenreId");

                    b.HasOne("DAL.Models.Author", "Translator")
                        .WithMany("TranslatedBooks")
                        .HasForeignKey("TranslatorId");

                    b.Navigation("Author");

                    b.Navigation("BookCoverage");

                    b.Navigation("Bookhouse");

                    b.Navigation("City");

                    b.Navigation("CurrentOwner");

                    b.Navigation("Genre");

                    b.Navigation("Language");

                    b.Navigation("SecondaryGenre");

                    b.Navigation("TertiaryGenre");

                    b.Navigation("Translator");
                });

            modelBuilder.Entity("DAL.Models.Bookhouse", b =>
                {
                    b.HasOne("DAL.Models.City", "City")
                        .WithMany("Bookhouses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("DAL.Models.City", b =>
                {
                    b.HasOne("DAL.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.HasOne("DAL.Models.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("DAL.Models.Author", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("TranslatedBooks");
                });

            modelBuilder.Entity("DAL.Models.BookCoverage", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DAL.Models.Bookhouse", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DAL.Models.City", b =>
                {
                    b.Navigation("Bookhouses");

                    b.Navigation("Books");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DAL.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("DAL.Models.Genre", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("SecondaryBooks");

                    b.Navigation("TertiaryBooks");
                });

            modelBuilder.Entity("DAL.Models.Language", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
