// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Libro_Swap.Migrations
{
    [DbContext(typeof(Libro_SwapDBContext))]
    [Migration("20210413191243_allow_empty_about_me")]
    partial class allow_empty_about_me
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("author_id");

                    b.Property<int>("BookCoverageId")
                        .HasColumnType("int")
                        .HasColumnName("book_coverage_id");

                    b.Property<int>("BookhouseId")
                        .HasColumnType("int")
                        .HasColumnName("bookhouse_id");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.Property<int>("CurrentOwnerId")
                        .HasColumnType("int")
                        .HasColumnName("current_owner_id");

                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasColumnName("genre_id");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int")
                        .HasColumnName("language_id");

                    b.Property<long>("Pages")
                        .HasColumnType("bigint");

                    b.Property<int?>("SecondaryGenreId")
                        .HasColumnType("int")
                        .HasColumnName("secondary_genre_id");

                    b.Property<int?>("TertiaryGenreId")
                        .HasColumnType("int")
                        .HasColumnName("tertiary_genre_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<bool>("Translation")
                        .HasColumnType("bit");

                    b.Property<int?>("TranslatorId")
                        .HasColumnType("int")
                        .HasColumnName("translator_id");

                    b.Property<long>("Year")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("BookCoverageId");

                    b.HasIndex("BookhouseId");

                    b.HasIndex("CityId");

                    b.HasIndex("CurrentOwnerId");

                    b.HasIndex("GenreId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("SecondaryGenreId");

                    b.HasIndex("TertiaryGenreId");

                    b.HasIndex("TranslatorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            BookCoverageId = 1,
                            BookhouseId = 1,
                            CityId = 4,
                            CurrentOwnerId = 4,
                            GenreId = 1,
                            LanguageId = 1,
                            Pages = 829L,
                            Title = "Амадока",
                            Translation = false,
                            Year = 2020L
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 5,
                            BookCoverageId = 1,
                            BookhouseId = 2,
                            CityId = 1,
                            CurrentOwnerId = 2,
                            GenreId = 1,
                            LanguageId = 1,
                            Pages = 815L,
                            Title = "Гаррі Поттер і Орден Фенікса",
                            Translation = true,
                            TranslatorId = 1,
                            Year = 2003L
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 5,
                            BookCoverageId = 2,
                            BookhouseId = 3,
                            CityId = 2,
                            CurrentOwnerId = 1,
                            GenreId = 1,
                            LanguageId = 2,
                            Pages = 766L,
                            Title = "Harry Potter and the Order of the Phoenix",
                            Translation = false,
                            Year = 2003L
                        });
                });

            modelBuilder.Entity("DAL.Models.BookAuthor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("author_name");

                    b.Property<string>("AuthorSurname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("author_surname");

                    b.HasKey("Id");

                    b.ToTable("BookAuthors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Софія",
                            AuthorSurname = "Андрухович"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Оксана",
                            AuthorSurname = "Забужко"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Луїза",
                            AuthorSurname = "Хей"
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "Вадим",
                            AuthorSurname = "Зеланд"
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "Джоан",
                            AuthorSurname = "Роулінг"
                        });
                });

            modelBuilder.Entity("DAL.Models.BookCoverage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoverageName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("coverage_name");

                    b.HasKey("Id");

                    b.ToTable("BookCoverages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverageName = "Тверда"
                        },
                        new
                        {
                            Id = 2,
                            CoverageName = "М'яка"
                        });
                });

            modelBuilder.Entity("DAL.Models.Bookhouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BookhouseName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("bookhouse_name");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Bookhouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookhouseName = "Видавництво Старого Лева",
                            CityId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookhouseName = "Видавництво Івана Малковича „А-ба-ба-га-ла-ма-га",
                            CityId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookhouseName = "Bloomsbury",
                            CityId = 3
                        });
                });

            modelBuilder.Entity("DAL.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("city_code");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("city_name");

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("CountryId");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityCode = "LV",
                            CityName = "Львів",
                            CountryId = 1
                        },
                        new
                        {
                            Id = 2,
                            CityCode = "KYI",
                            CityName = "Київ",
                            CountryId = 1
                        },
                        new
                        {
                            Id = 3,
                            CityCode = "LND",
                            CityName = "Лондон",
                            CountryId = 2
                        },
                        new
                        {
                            Id = 4,
                            CityCode = "PRS",
                            CityName = "Париж",
                            CountryId = 4
                        });
                });

            modelBuilder.Entity("DAL.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("country_code");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("country_name");

                    b.HasKey("Id");

                    b.ToTable("LibCountries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryCode = "UA",
                            CountryName = "Україна"
                        },
                        new
                        {
                            Id = 2,
                            CountryCode = "EN",
                            CountryName = "Англія"
                        },
                        new
                        {
                            Id = 3,
                            CountryCode = "SCOT",
                            CountryName = "Шотландія"
                        },
                        new
                        {
                            Id = 4,
                            CountryCode = "FR",
                            CountryName = "Франція"
                        });
                });

            modelBuilder.Entity("DAL.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("genre_name");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GenreName = "Проза"
                        },
                        new
                        {
                            Id = 2,
                            GenreName = "Поезія"
                        },
                        new
                        {
                            Id = 3,
                            GenreName = "Драматургія"
                        });
                });

            modelBuilder.Entity("DAL.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("language_code");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("language_name");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LanguageCode = "UKR",
                            LanguageName = "Українська"
                        },
                        new
                        {
                            Id = 2,
                            LanguageCode = "ENG",
                            LanguageName = "Англійська"
                        },
                        new
                        {
                            Id = 3,
                            LanguageCode = "FRA",
                            LanguageName = "Французька"
                        },
                        new
                        {
                            Id = 4,
                            LanguageCode = "CHI",
                            LanguageName = "Китайська"
                        });
                });

            modelBuilder.Entity("DAL.Models.Libro_SwapUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AboutMe")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("about_me");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("city_id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Recommendation")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("recommendation");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AboutMe = "Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.",
                            AccessFailedCount = 0,
                            CityId = 4,
                            ConcurrencyStamp = "facc5d74-8db5-4338-9e56-121c857a3870",
                            Email = "mbeecker8@deviantart.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Cardify"
                        },
                        new
                        {
                            Id = 2,
                            AboutMe = "Pellentesque ultrices mattis odio. Donec vitae nisi.",
                            AccessFailedCount = 0,
                            CityId = 3,
                            ConcurrencyStamp = "a9906d89-a8b7-4784-b866-0cb45f318dfa",
                            Email = "ktolmanm@php.net",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Voyatouch"
                        },
                        new
                        {
                            Id = 3,
                            AboutMe = "Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b2e72db5-3a2c-4786-bb1f-54366da81c87",
                            Email = "tcothey1t@gmpg.org",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Konklab"
                        },
                        new
                        {
                            Id = 4,
                            AboutMe = "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.",
                            AccessFailedCount = 0,
                            CityId = 2,
                            ConcurrencyStamp = "66721196-e4e6-4356-b6e7-1c10be8b7660",
                            Email = "jmundow1y@sfgate.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Ronstring"
                        },
                        new
                        {
                            Id = 5,
                            AboutMe = "In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
                            AccessFailedCount = 0,
                            CityId = 1,
                            ConcurrencyStamp = "51fe222f-b91c-44a9-aef4-2fe661145e78",
                            Email = "tshimman1a@wp.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "Flowdesk"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("DAL.Models.Book", b =>
                {
                    b.HasOne("DAL.Models.BookAuthor", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.BookCoverage", "BookCoverage")
                        .WithMany("Books")
                        .HasForeignKey("BookCoverageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Bookhouse", "Bookhouse")
                        .WithMany("Books")
                        .HasForeignKey("BookhouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.City", "City")
                        .WithMany("Books")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DAL.Models.Libro_SwapUser", "CurrentOwner")
                        .WithMany("Books")
                        .HasForeignKey("CurrentOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Language", "Language")
                        .WithMany("Books")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Genre", "SecondaryGenre")
                        .WithMany("SecondaryBooks")
                        .HasForeignKey("SecondaryGenreId");

                    b.HasOne("DAL.Models.Genre", "TertiaryGenre")
                        .WithMany("TertiaryBooks")
                        .HasForeignKey("TertiaryGenreId");

                    b.HasOne("DAL.Models.BookAuthor", "Translator")
                        .WithMany("TranslatedBooks")
                        .HasForeignKey("TranslatorId");

                    b.Navigation("Author");

                    b.Navigation("BookCoverage");

                    b.Navigation("Bookhouse");

                    b.Navigation("City");

                    b.Navigation("CurrentOwner");

                    b.Navigation("Genre");

                    b.Navigation("Language");

                    b.Navigation("SecondaryGenre");

                    b.Navigation("TertiaryGenre");

                    b.Navigation("Translator");
                });

            modelBuilder.Entity("DAL.Models.Bookhouse", b =>
                {
                    b.HasOne("DAL.Models.City", "City")
                        .WithMany("Bookhouses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("DAL.Models.City", b =>
                {
                    b.HasOne("DAL.Models.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("DAL.Models.Libro_SwapUser", b =>
                {
                    b.HasOne("DAL.Models.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("DAL.Models.Libro_SwapUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("DAL.Models.Libro_SwapUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Libro_SwapUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("DAL.Models.Libro_SwapUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Models.BookAuthor", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("TranslatedBooks");
                });

            modelBuilder.Entity("DAL.Models.BookCoverage", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DAL.Models.Bookhouse", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DAL.Models.City", b =>
                {
                    b.Navigation("Bookhouses");

                    b.Navigation("Books");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DAL.Models.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("DAL.Models.Genre", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("SecondaryBooks");

                    b.Navigation("TertiaryBooks");
                });

            modelBuilder.Entity("DAL.Models.Language", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("DAL.Models.Libro_SwapUser", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
